{% set python_min = '3.10' %}
{% set name = "MLWC" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ToAmano/{{ name }}/archive/refs/tags/v.{{ version }}.tar.gz
    sha256: 30cdb6a21df5ae68b80f87b4ae240c12913e9be2a9dd3166ca9c95bc2ceeed13

build:
  number: 2
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --prefix=$PREFIX

requirements:
  host:
    - python {{ python_min }}
    - rdkit >=2023.03.0
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.5
    - pytorch
    - torchinfo
    - ase ==3.23.0
    - rdkit >=2023.03.0
    - mdtraj
    - pyyaml
    - statsmodels
    - matplotlib-base
    - mdanalysis
    - packmol
    - jaxtyping

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - CPextract.py --help
    - CPmake.py --help
    - CPtrain.py --help
    - python -c "import torch; print(torch.cuda.is_available())"
about:
  home: https://github.com/ToAmano/MLWC
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: "A machine learning package for Wannier centers."

extra:
  recipe-maintainers:
    - ToAmano
